image_pipeline/enhancer:
  ros__parameters:
    in_topic: in
    out_topic: out
    algorithm: udcp # udcp se_avg se_pca

image_pipeline/pipe_detector:
  ros__parameters:
    in_topic: out
    out_topic: outout
    hue_min: 0
    sat_min: 0
    val_min: 0
    hue_max: 0
    val_max: 0
    sat_max: 0

image_pipeline/buoy_detector:
  ros__parameters:
    in_topic: ininin
    out_topic: outoutout
    red_buoy: [0, 0, 0, 0, 0, 0] # The order is [hue_min, sat_min, val_min, hue_max, val_max, sat_max]
    blue_buoy: [0, 0, 0, 0, 0, 0]
    yellow_buoy: [0, 0, 0, 0, 0, 0]
