/**:
  ros__parameters:
    heartbeat_rate: 100

image_pipeline/color_enhancer:
  ros__parameters:
    in_topic: /camera/image_raw
    out_topic: /camera/enhanced/image_raw

    algorithm: udcp
    heartbeat_topic: /image_pipeline/color_enhancer/heartbeat
    show_result: false

image_pipeline/segmentation_calibrator:
  ros__parameters:
    in_topic: /camera/enhanced/image_raw

image_pipeline/pipe_detector:
  ros__parameters:
    in_topic: /camera/enhanced/image_raw
    out_topic: pipe_direction
    heartbeat_topic: /image_pipeline/pipe_detector/heartbeat
    show_result: false
    hue_min: 0
    sat_min: 0
    val_min: 172
    hue_max: 255
    val_max: 255
    sat_max: 255
image_pipeline/buoy_detector:
  ros__parameters:
    in_topic: /camera/enhanced/image_raw
    out_topic: buoy_detector/out
    min_buoy_radius_px: 10
    max_buoy_radius_px: 500
    blob_dilation_size: 15
    blob_median_blur_size: 15
    show_result: false
    heartbeat_topic: /image_pipeline/buoy_detector/heartbeat
    red_buoy:
      - 137
      - 125
      - 39
      - 196
      - 255
      - 253
    white_buoy:
      - 0
      - 0
      - 139
      - 166
      - 50
      - 255
    yellow_buoy:
      - 9
      - 126
      - 104
      - 39
      - 255
      - 255
    black_buoy:
      - 13
      - 0
      - 0
      - 148
      - 53
      - 37
    orange_buoy:
      - 18
      - 67
      - 101
      - 55
      - 255
      - 215

image_pipeline/yolo_model:
  ros__parameters:
    engine: cuda
    in_topic: /camera/image_raw
    out_topic: yolo_detected
    out_detection: /camera/yolo_detections
    cuda_model_path: /home/jetson/ros2_ws/src/image_pipeline/yolo_model/models/buoy_improvement.onnx
    tensorrt_model_path: /home/jetson/ros2_ws/src/image_pipeline/yolo_model/models/
    heartbeat_topic: /image_pipeline/yolo_model/heartbeat
    classes:
      - "0"
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
      - "6"
      - "7"
      - "8"
      - "9"
      - "buoy"
      - "console_red_background"
      - "humans"

image_pipeline/buoy_color:
  ros__parameters:
    in_image_topic: /camera/image_raw
    in_detection_topic: /camera/yolo_detections
    out_topic: /camera/object_colors
    hist_paths:
      - /home/jetson/ros2_ws/src/image_pipeline/buoy_color/hist/red_histograms.json
      - /home/jetson/ros2_ws/src/image_pipeline/buoy_color/hist/white_histograms.json
      - /home/jetson/ros2_ws/src/image_pipeline/buoy_color/hist/yellow_histograms.json
    json_file_path: /home/jetson/ros2_ws/src/image_pipeline/buoy_color/config/color_weigths.json
    hist_threshold: 0.9
    min_votes_required: 2
    show_debug_prints: false
    show_results: false
    heartbeat_topic: /image_pipeline/buoy_color/heartbeat

image_pipeline/camera_info_publisher:
  ros__parameters:
    timer_period_milliseconds: 500
    camera_info_out: /camera/camera_info
    heartbeat_topic: /image_pipeline/camera_info_publisher/heartbeat

image_pipeline/image_getter:
  ros__parameters:
    heartbeat_topic: /image_pipeline/image_getter/heartbeat
    image_topic: /camera/image_raw
    timer_period: 100

image_pipeline/watchdog:
  ros__parameters:
    timeout_milliseconds: 1000
    watchdog_checking_rate: 500
    topics_to_monitor:
      - /image_pipeline/color_enhancer/heartbeat
      - /image_pipeline/yolo_model/heartbeat
      - /image_pipeline/buoy_color/heartbeat
      - /image_pipeline/camera_info_publisher/heartbeat
      - /image_pipeline/marine_tracking_node/heartbeat
      - /image_pipeline/marine_detector_node/heartbeat
      - /image_pipeline/image_getter/heartbeat
    out_topic: /auv/image_pipeline/heart_beat
