image_pipeline/color_enhancer:
  ros__parameters:
    in_topic: fake_video
    out_topic: color_enhancer/result
    algorithm: udcp
    show_result: true
image_pipeline/segmentation_calibrator:
  ros__parameters:
    in_topic: color_enhancer/result
image_pipeline/pipe_detector:
  ros__parameters:
    in_topic: color_enhancer/result
    out_topic: pipe_direction
    show_result: true
    hue_min: 0
    sat_min: 0
    val_min: 172
    hue_max: 255
    val_max: 255
    sat_max: 255
image_pipeline/buoy_detector:
  ros__parameters:
    in_topic: color_enhancer/result
    out_topic: buoy_detector/out
    min_buoy_radius_px: 10
    max_buoy_radius_px: 500
    blob_dilation_size: 15
    blob_median_blur_size: 15
    show_result: false
    red_buoy:
      - 137
      - 125
      - 39
      - 196
      - 255
      - 253
    white_buoy:
      - 0
      - 0
      - 139
      - 166
      - 50
      - 255
    yellow_buoy:
      - 9
      - 126
      - 104
      - 39
      - 255
      - 255
    black_buoy:
      - 13
      - 0
      - 0
      - 148
      - 53
      - 37
    orange_buoy:
      - 18
      - 67
      - 101
      - 55
      - 255
      - 215

image_pipeline/yolo_model:
  ros__parameters:
    engine: cuda
    in_topic: color_enhancer/result
    out_topic: yolo_detected
    cuda_model_path: /home/tonelllo/ros2_ws/src/image_pipeline/yolo_model/models/best.onnx
    classes:
      - Damaged_pipe
      - number1,
      - number2
      - number3
      - number4
      - red_b_number_3
      - red_b_number_4
      - red_b_number_5
      - red_b_number_6
      - red_bouy
      - white_bouy
      - yellow_bouy
