image_pipeline/color_enhancer:
  ros__parameters:
    in_topic: fake_video
    out_topic: color_enhancer/result
    algorithm: udcp
image_pipeline/segmentation_calibrator:
  ros__parameters:
    in_topic: color_enhancer/result
image_pipeline/pipe_detector:
  ros__parameters:
    in_topic: color_enhancer/result
    out_topic: pipe_direction
    hue_min: 59
    sat_min: 71
    val_min: 56
    hue_max: 255
    val_max: 255
    sat_max: 255
image_pipeline/buoy_detector:
  ros__parameters:
    in_topic: ininin
    out_topic: outoutout
    red_buoy:
      - 0
      - 0
      - 0
      - 255
      - 255
      - 255
    white_buoy:
      - 37
      - 76
      - 44
      - 226
      - 255
      - 255
    yellow_buoy:
      - 37
      - 0
      - 44
      - 255
      - 255
      - 255
    black_buoy:
      - 37
      - 0
      - 0
      - 255
      - 255
      - 255
    orange_buoy:
      - 37
      - 76
      - 44
      - 255
      - 255
      - 255
image_pipeline/number_detector:
  ros__parameters:
    in_topic: inininin
