name: Humble build test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
      - uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: image_pipeline_launcher
          target-ros2-distro: humble
