name: Humble build test
on:
  push:
  pull_request:
    branches:
      - main

jobs:
  humble_install:
    runs_on: ubuntu-latest
    container:
      image: ubuntu:noble
    steps:
      - uses: actions/checkout@v3
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
      - uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: image_pipeline_launcher
          target-ros2-distro: humble
